apiVersion: v1
kind: Pod
metadata:
  name: customer-pod
  # namespace: projecta
  labels:
    app: packersmovers    
spec:
  containers:
  - name: customer
    image: 851271747310.dkr.ecr.us-east-2.amazonaws.com/customer:1
    ports:
    - containerPort: 8080
  - name: webapp
    image: nginx
    ports:
    - containerPort: 80

