# Command for base64 encoding: " echo -n 'Hello, World!' | base64 "
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-username: bmF2ZWVudXBwYWxh
  db-password: YXdzI2Rldm9wcw==
