apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
    serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: ebs-claim 
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: db-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: db-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: db-password
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql